import './globals.css'
import Providers from './Providers';
import Navbar from '@/components/Navbar';
export const metadata = {
  title: 'Sistema de logueo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <Navbar/>
          <div className="container mx-auto">{children}</div>
        </Providers>
      </body>
    </html>
  )
}
